### ISSUE TITLE
Est-ce qu'on présente les concepts comme master, origin, upstream...?

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/git-cheatsheet#4]

**Comment by fxleblanc** [comment]
Selon moi, ce serait plutôt une cheatsheet pour faire un flot de contribution à des projets. Concrètement, on pourrait faire un page 2 qui montrent les différents pour contribuer et maintenir un projet(e.g. faire les merges, rebase, etc...). La configuration des branches upstream et origin seraient donc dans cette page.

**Comment by luctrudeau** [comment]
J'aime bien cette idée, cette page pourrait aussi contenir des instructions pour gérer un merge conflict (la bête noir de plusieurs débutants).

**Comment by fxleblanc** [comment]
En effet. Très bonne idée. Tu avais mentionné l'exemple d'un Hello world si je me souviens bien. On pourrait faire un exemple avec des screenshots. Ce serait un peu gros sur la feuille par contre sauf si on dédie une page entière à ça.

**Comment by luctrudeau** [comment]
Screenshot? je ne comprend pas, je l'aurais fait en texte:

```
the number of planets are
<<<<<<< HEAD
nine
=======
eight
>>>>>>> branch-
```

**Comment by fxleblanc** [comment]
Bien sûr. j'ai compliqué les choses pour rien ;).
