### ISSUE TITLE
Numéro de version sur le git-cheatsheet

### ISSUE THREAD

**Issue by luctrudeau** [MaisonLogicielLibre/git-cheatsheet#8]
Est-ce qu'on devrait avoir un numéro de version sur la cheatsheet afin de permettre aux utilisateurs de suivre les versions?

Est-ce qu'on label certains builds en fonction des version de la cheatsheet. Ex: version: 0.1

**Comment by fxleblanc** [comment]
On pourrait utiliser le tagging de git et ne pas avoir à spécifier les versions dans le fichier lui-même.
